#!/bin/bash
# gen_tickets.sh — Issue Ticket Generator
# Loggy v6.0 — Phase 9
#
# Generates one ticket per issue in multiple formats:
# Markdown, Jira CSV, GitLab JSON.

generate_tickets() {
    local dev_id datestamp ticket_dir
    dev_id=$(get_sysinfo device_id)
    [ -z "$dev_id" ] || [ "$dev_id" = "unknown" ] && dev_id="unknown"
    datestamp=$(date +%Y%m%d_%H%M)
    ticket_dir="${OUTPUT_DIR}/tickets_${dev_id}_${datestamp}"
    mkdir -p "$ticket_dir"

    if [ ! -f "$ISSUES_FILE" ] || [ ! -s "$ISSUES_FILE" ]; then
        log_warn "No issues to generate tickets for"
        return 1
    fi

    local count=0

    # ─── Individual Markdown Tickets ────────────────────────────────────
    while IFS=$'\t' read -r sev comp title desc evfile; do
        [ -z "$sev" ] && continue
        count=$((count + 1))
        local slug
        slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g' | sed 's/__*/_/g' | head -c 50)
        local ticket_file="${ticket_dir}/ticket_${count}_${slug}.md"

        {
            printf "# %s\n\n" "$title"
            printf "| Field | Value |\n|---|---|\n"
            printf "| Priority | %s |\n" "$sev"
            printf "| Component | %s |\n" "$comp"
            printf "| Device | %s |\n" "$dev_id"
            printf "| Firmware | %s |\n" "$(get_sysinfo fw_version)"
            # Connector attribution (if identifiable from title/desc)
            local _conn_attr=""
            if echo "$title $desc" | grep -qiE 'connector.?1|InnerSM.?1|evse.?1'; then
                _conn_attr="Connector 1"
            elif echo "$title $desc" | grep -qiE 'connector.?2|InnerSM.?2|evse.?2'; then
                _conn_attr="Connector 2"
            fi
            [ -n "$_conn_attr" ] && printf "| Connector | %s |\n" "$_conn_attr"
            printf "| Detected | %s |\n\n" "$(date '+%Y-%m-%d %H:%M')"

            printf "## Description\n\n"
            # Split description: main text vs troubleshooting vs on-site flag
            local main_desc="" ts_text="" onsite_flag=""
            if echo "$desc" | grep -q 'Troubleshooting:'; then
                main_desc=$(echo "$desc" | sed 's/ *Troubleshooting:.*//')
                ts_text=$(echo "$desc" | grep -oP 'Troubleshooting:.*' | sed 's/\[On-site service.*//;s/ *$//')
            else
                main_desc="$desc"
            fi
            echo "$desc" | grep -q '\[On-site service' && onsite_flag="yes"

            printf "%s\n\n" "$main_desc"

            if [ -n "$ts_text" ]; then
                printf "## Troubleshooting Steps\n\n"
                # Convert "1. X 2. Y" to numbered list
                echo "$ts_text" | sed 's/^Troubleshooting: //' | sed 's/ \([0-9]\+\)\. /\n\1. /g' | while IFS= read -r line; do
                    [ -n "$line" ] && printf "%s\n" "$line"
                done
                printf "\n"
            fi

            if [ -n "$onsite_flag" ]; then
                printf "> ⚠️ **On-site service required** — this issue cannot be resolved remotely.\n\n"
            fi

            # Signature match
            if [ -f "${SIGNATURES_DIR:-}/known_signatures.tsv" ]; then
                while IFS=$'\t' read -r sig_pattern sig_comp sig_sev sig_title sig_cause sig_fix sig_url; do
                    [ -z "$sig_pattern" ] && continue
                    [[ "$sig_pattern" == \#* ]] && continue
                    if echo "$title $desc" | grep -qi "$sig_pattern"; then
                        printf "## Root Cause\n\n%s\n\n" "$sig_cause"
                        printf "## Recommended Fix\n\n%s\n\n" "$sig_fix"
                        [ -n "$sig_url" ] && printf "## Reference\n\n%s\n\n" "$sig_url"
                        break
                    fi
                done < "${SIGNATURES_DIR}/known_signatures.tsv"
            fi

            # Evidence
            if [ -n "$evfile" ] && [ -f "$evfile" ]; then
                printf "## Evidence\n\n\`\`\`\n"
                head -40 "$evfile"
                local total
                total=$(wc -l < "$evfile" 2>/dev/null | tr -d ' ')
                [ "${total:-0}" -gt 40 ] && printf "\n... %d more lines\n" "$((total - 40))"
                printf "\`\`\`\n"
            fi

            printf "\n---\n*Generated by Loggy v%s*\n" "$ANALYZER_VERSION"
        } > "$ticket_file"
    done < "$ISSUES_FILE"

    # ─── Jira CSV ───────────────────────────────────────────────────────
    local jira_file="${ticket_dir}/jira_import.csv"
    {
        printf "Summary,Priority,Component,Description,Labels\n"
        while IFS=$'\t' read -r sev comp title desc evfile; do
            [ -z "$sev" ] && continue
            local jira_prio="Medium"
            [ "$sev" = "CRITICAL" ] && jira_prio="Highest"
            [ "$sev" = "HIGH" ] && jira_prio="High"
            [ "$sev" = "LOW" ] && jira_prio="Low"
            local csv_title csv_desc csv_labels
            csv_title=$(echo "$title" | sed 's/"/""/g')
            csv_desc=$(echo "$desc" | sed 's/"/""/g')
            csv_labels="iotecha,log-analyzer,$dev_id"
            echo "$desc" | grep -q '\[On-site service' && csv_labels="$csv_labels,on-site-service"
            printf '"%s","%s","%s","%s","%s"\n' \
                "$csv_title" "$jira_prio" "$comp" "$csv_desc" "$csv_labels"
        done < "$ISSUES_FILE"
    } > "$jira_file"

    # ─── GitLab JSON ────────────────────────────────────────────────────
    local gl_file="${ticket_dir}/gitlab_issues.json"
    {
        echo '['
        local first=1
        while IFS=$'\t' read -r sev comp title desc evfile; do
            [ -z "$sev" ] && continue
            [ "$first" -eq 1 ] && first=0 || echo ','
            local labels="iotecha,${sev,,}"
            echo "$desc" | grep -q '\[On-site service' && labels="$labels,on-site-service"
            printf '  {"title":"%s","description":"%s","labels":"%s"}' \
                "$(echo "$title" | sed 's/"/\\"/g')" \
                "$(echo "[${sev}] ${comp}\\n\\n${desc}" | sed 's/"/\\"/g')" \
                "$labels"
        done < "$ISSUES_FILE"
        echo ''
        echo ']'
    } > "$gl_file"

    log_ok "Tickets: $count issues → $ticket_dir/"
    log_info "  Markdown: ${count} individual files"
    log_info "  Jira CSV: jira_import.csv"
    log_info "  GitLab:   gitlab_issues.json"
}
